# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4b4393db39fd858132dbaf4bb74e27713d5e96670e14b6d8f4f941ae2c6585c0d4c5d1a51c2f5a64781d7bf8c311bf7f7a3dd78493e1954817cb9aa45322c764

test:
  secret_key_base: 5886d4184aef834f7a568904ce0ca4f13bcdbb2caa860fe96861ea2014feed4b6650ac1d1a90447232bb2850d50e94c8984abd17b8d231634782695e9c175d00

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
